# This is a basic workflow to help you get started with Actions

name: Android CI

on: 
 push: 
 branches: 
 - 'master'

 workflow_dispach:
 inputs:
  app_id:
    description: 'The application Id of the current build'
    required: true
 branch:
    description: 'The branch from which we have to build'
    required: true
    
jobs:
  build: 
   name: Setup Enviornmnet and build
   runs-on : ubuntu-latest
   steps: 
     -name: checkout the code to specific branch
     uses: actions/checkout@v2
     with:
      ref: ${{ github.event.inputs.branch }}

    - name: Set up JDK
     uses: actions/setup-java@v2
     with:
      distribution: 'zulu'
      java-version: '11'

    - name: Setup Android sdk
      user: android-actions/setup-android@v2

    - name: Make gradlew executable
     run: chmod +x ./gradlew

      
      
